### ISSUE TITLE
Can't build project with xstream on NetBeans 11.3

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/pepperModules-HeadMarkerModule#1]
@thomaskrause I'm having trouble building this project with the latest NetBeans. I'm getting:

```
generate failure: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.carrotgarden.osgi.anno.scr.util.UtilAsm.classNode(UtilAsm.java:235)
	at com.carrotgarden.osgi.anno.scr.make.Builder.makeComponent(Builder.java:559)
	at com.carrotgarden.osgi.anno.scr.make.Builder.makeAggregator(Builder.java:536)
	at com.carrotgarden.osgi.anno.scr.make.Maker.make(Maker.java:142)
	at com.carrotgarden.maven.scr.CarrotOsgiScrGenerate.processClassFolder(CarrotOsgiScrGenerate.java:319)
	at com.carrotgarden.maven.scr.CarrotOsgiScrGenerate.execute(CarrotOsgiScrGenerate.java:102)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

The error triggers on the pom file, but I can't see a reference to xstream anywhere (in the pom or otherwise in the project). Does some dependency need to be updated?

**Comment by thomaskrause** [comment]
This is a problem with one of the used Maven build plugins which parses the generated class-files. The older version of this build plugin was released before Java 11 and does not know about the new class-file format of Java 8. The dependency is brought in transitively from the `pepper-parentModule` (which is the parent project for all modules) and it can be fixed by updating the version of the parent module. I committed a fix to the master branch.

**Comment by amir-zeldes** [comment]
Thanks for the quick fix! This resolved the initial error, but now I'm getting:

```
[0:0]: generate failure: java.lang.IllegalArgumentException: Unsupported class file major version 58
java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)
	at com.carrotgarden.osgi.anno.scr.util.UtilAsm.classNode(UtilAsm.java:235)
	at com.carrotgarden.osgi.anno.scr.make.Builder.makeComponent(Builder.java:559)
	at com.carrotgarden.osgi.anno.scr.make.Builder.makeAggregator(Builder.java:536)
	at com.carrotgarden.osgi.anno.scr.make.Maker.make(Maker.java:142)
	at com.carrotgarden.maven.scr.CarrotOsgiScrGenerate.processClassFolder(CarrotOsgiScrGenerate.java:319)
	at com.carrotgarden.maven.scr.CarrotOsgiScrGenerate.execute(CarrotOsgiScrGenerate.java:102)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by thomaskrause** [comment]
What Java Versio are you using for compilation? From the error message it seems like this is Java 14, which is also quite new and it might have the same issue as we had with Java 11. You can also set the JAVA_HOME variable to a Java 11 or 8 installation before running Maven in case you have multiple Java versions.

**Comment by amir-zeldes** [comment]
I was using jdk-14, so I switched to 11, but now I get:

```
Failed to execute goal org.apache.maven.plugins:maven-source-plugin:2.4:jar-no-fork (attach-sources) on project pepperModules-HeadMarkerModule: Execution attach-sources of goal org.apache.maven.plugins:maven-source-plugin:2.4:jar-no-fork failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.4:jar-no-fork: java.lang.ExceptionInInitializerError: null
```

I looked this up and tried the following:
  * Make sure Java is set to JDK 11 in global NetBeans options, Run configuration for the build, and every single option I could find anywhere
  * Completely reinstall NetBeans with JDK 11 as Java home and in Path
  * Delete .m2 folder and re-build with dependencies
  * Manually replace bundled maven with a fresh install from Apache

And sadly I still get the error, and I'm out of ideas... Any thoughts?

**Comment by amir-zeldes** [comment]
OK, I just downgraded to JDK 1.8 and it compiles fine. I also discovered I can't run Pepper in general under Open JDK11, is that a known issue?

**Comment by thomaskrause** [comment]
I added support for Java 11 in https://github.com/korpling/pepper/pull/124/files (seen the changes in the pepper.sh file), but I might have missed porting these changes to the other startup scripts

**Comment by amir-zeldes** [comment]
I'm running it under Win10/64 using `pepperStart.bat -p  xyz.pepperparams`, should I edit something there?
